export const FETCH_POSTS= 'FETCH-POSTS';
export const FETCH_POST= 'FETCH-POST';
export const FETCH_POSTS_LOADER= 'FETCH_POSTS_LOADER-POSTS';
export const FETCH_POST_LOADER= 'FETCH_POST_LOADER-POST';
export const NEW_POST= 'NEW-POST';
export const ADD_TO_CART= 'ADD_TO_CART';
export const REMOVE_POST = 'REMOVE_POST';
export const UPDATE_CART = 'UPDATE_CART';
export const GET_SINGLE_PRODUCT ='GET_SINGLE_PRODUCT';
export const GET_QUANTITY = 'GET_QUANTITY';
export const USER_AUTHENTICATION = 'USER_AUTHENTICATION';


